language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: PEz6p5mupUfPFysVZVZh/XDQmZCkh6oT59fUJjfFId/1p031iUF7qlDQpxb/mgOyni3rYEDXXS6yrDJBE3uGeS+hepTqgvg5OyfJGnXaI/xxqaDMxJ+rnjsERyCkYbKsj99uTysHpJiHohlNoXJlfJq4CgJN694psMrRuzXBM22+YKIWW/k6LpuhBnrc/dKLNYW6fd8xMkh1XidVJ/idZ4ChAEQCrYnBEU0yIkHp52jy8WwjodCP98V1T4uuwe1Zv/pbZFYyiuu2PBO8BovlkC/VfK7p+p7IQOTYCnvIZ4ExG/IVBK65QE1OFLvKVfwJN4UGzKdCUWt6jq+LG6IV/hDZDvoyZvIYqC2BJO+xfs7ecXBfzEBiRsyvRz9rNmESO2bnWFVX7AhjAmPPmbKR5pZdQPRkKIlAkP45Qk/F6hVOeo8uP09a+xQUNIfUUV6outxukyYxWsuaaYuh4nYu3JHp1k3ycCqxTVmgOOFGVdTdD3LwwhZ/Hz7UhY41AWkZ88g6ul/klKUKYx9XZ06aKu09itW+mzLQvYsKH/r/promno+6pvdVgLvtdf5Kxc4ZY4ybUtLMjNwmMsbuxeNxMGESfIR+6j0RgucRce3dLY8tChoIUlbxacCxoWCnTHb87sJJXX1PbSnhKEGpNvIQdi8vtIaJJTORIO1MPiz2etE=
  - secure: YhjNKehicmjqr/oWs7ewEXR9MMgYjlrhCjDvErjS/I/Lo2B6kRyKbZbwz9N5nvs98NsQProEySsV+xuaRs5Ieu397OgLQeDrvAU/zrh7QouRwimIf7ZFbbSe9bjrqJDDTknKbGRajrGRDdcnK1ImPurLOYqiuRlIBdV91xwS/+gvUhMf/hgkcu0zWJQ7EDV4VRJIbdjgt6gTKQMI8EXRKg6doKSR10+PTrgFZ8sv27QdFlxQWUdibvi6egpTJVJYOng5cvBGLHnPpMEORbkCQfv79w06H4/Yq87yHKTTPHLvqLrT3g0dSleQb64CV1Yiq5jcA+ofR80sspVvDcwUAGtOtFjy/Meoi6gxkC8wlVTiMH3oTm0gJ9scD6Rx9CxDkeWP6AdH4W6j1PCXjslfiP1wpXVztpYxVXcKGF+4V81R1lqMUXhpUtqQ1Iwhuxk4DWeUHqenl0d94NefB1ahWlPuXKTeGHQ3hmrDOZXQoV+YBSAn7bTjjCxNr4UQrIeXvTZ0VsIknrdKwgFKlu3U8JjRDdXbIdhdKI5DgetILNbDTd0B0+kCDP7tPfUK3qe9VdR7LTZlL0XP4vhbelIZ2pkWPtQBGSrr8LU8sp2lacdahLAl8WUTIccDLTSbzvbXmKKZY/btN0IW4v7i4xCJFuAsesp2fIerxeVQeqIwtfY=
  - secure: GKZuK1x6fFcZ8CEy/KWh7T04rMX4tKf8JyXXFUQqnjMpdM+09BFXR1DY8ZSqpCrqlUr9evOlFcvgCqTBcYPnlJHXiYuxpi/DJk0sJU3D88FzPLWY6C/7G7YyJ7kejy+gD+LQZwB/Xe9id3zEQc0dFX/W3RsixjMBenbJvqsqT5P3e2EA3CU4eFSaHHV/pLaroZNTzreivVHA7cqBC//0zRUWw4654OirwRypErf430JEwkTXJk/vZppXrSRHoXqqrjD9iF8ALXNRfIfsN58fNd48G2f90UntXALaQQtyGz5wEILZvxesMyCcNNdABhKBvic1n2aBz/+MzK3hIkiswMtkzAkzlyv9jo8ceYUxoaXxQ1EezJADcuaYhSC+EhyWvZL16ZDY7s9yr/PUEriX7ESIcijjz+wglHk1mb5KO9F1rtGFh2vANjj8hKQNh92li0RhipqYCVKvh0OOXA6T+YrcKMvZuoXsJNg3peKF0OAkfxBz7toFbM5/BNFVrWDIO3Q1h2nWyhFr7FHcwNDGJasIuOz3vtqRu4ZP5BgcAd4+IUj4IgUrNI9Bods/tTPJoPFBsOexDjhDP8sQdtONhzzdFIcNhQKxpD+oyLZAVzhfGbOvUlEsMKxwHwhoAjEEr0DCHzuIoZgEVU8VO7teFEYcsrK+31V2zgvvU6qc01I=
before_install:
- export TZ=Pacific/Noumea
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Y1R5rIFvD964S0K5nGkNtJhRWCbbO5to3hYNQhsloCJH9SQ7xxC20WmAqxCkS1ydDzFKkuAz6BB+MWKvSVGLK9Dwh/UZpNbnCncMLRdR457jpkGYMgNfb+Bf7JZ4osepDP88rULnDTxnYj3GmCzLgDditUBKpXkHqU90yP3dsCXjSjpe/RHcM7wdhPEDf5CWSQj2fasiqm42H7QvjdkzNcuGv1aqVw9SQ9fHtSVkpuTSsDYqcY+p6ojnaF3GkcnmcwPHSd9kkYI99YZU0jD2NSoNMGmlqqIuQezOTEM3Q50leE69li07tV+X/ETdIqNFiDZNSLi6B+tzWroqoRBYkRmtJaymKvLP0V+25uKaeLFYocQcCt93qhcCP2IUEdHbJRV7PzOr9vZ8JOdoysXB8gf/X+Cs/3CIRVW1AIM6+9dJ1wJ5TrndfzsrZsqIg41SjPUVQpsqAI+iHhWBVCCXwaX8kX5HtkAiaYTNx2rGYUZ2PZAGXB2Yd8Fa/MIPk0YfHaGjqKeYE2PJUDD3vaPad4K7DKYsSY1Hsubg0oxf9Rnp2iHOQWu0paFTelanvTssNkk9mQTj62cvT9OS07UgAYXAGg1vJVmsjGt9byNU8Q7sltV+/nw77XpUAAz6ky9VHXTuOn7m+5/8sXY550uriy1hsYy0jlTs5zgLEIUq27Y=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-abs-ws
notifications:
  slack:
    secure: e2F8SjvwWvBiuaJ1NmIT+6GiNdvIfLGFusf5UU9dERh+VmoaoDwwdElmOGU4b9yz4xnGGp2iqVaJ/Oyvw1s9ErMRSVCvlNHEpShSi9YfTd3JyrxNJx8xm9DaTaF+S4LRfRFuyB9f+LFtWpEUkD3E8wjZXWaBHU8t5ynA/bpaxM7wngq17UFOGT5Fq9qIJz058KAv0ufUxzjYQDRXy2j10qyKM6cIXAUYOulOD7d5QmhM4ATQrwvxtLMw5iQG3FXvoWXw7zRlnK8cQC0KFC9/oY33g1NQZXzQwvzfK6UiZZOTO8D3CUasxbQk6Cy4EH0x0ppxkJMhS7RbFPUIVAX/Dui7xJoMfbOpqP6OHp4yfRxiUvqbQWu5taLZBoRz46596+ZzlQfLw1Q8fnXsp8dKpXJZuAuaqrwqMLWo6yzRdST6gn4zzSGoxluBUm8gI81CynjvCEN+Rybf8bIiXdOFEqqtnOCWElGJXHsnCSCCaFvBFU7ubJ1Cm6OC49UEJ4YXIW4GRKl3+J++5zyURWf8Ar09ndSfB6t7rnDRuYYKbkcmqTe5RrRHtdMcwSq/ppkyf0yn7tnBdo36tpPpaspFAusa3xYtVVkc2t8O+wSnKyJjZofD/5e9n1uA0v/LrpR5aRTlFYAlyQBtXcurLQL86fhg8/p6Xibog0ZpxJvHS+E=
