// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;
import nc.noumea.mairie.abs.domain.AgentWeekReposComp;

privileged aspect AgentWeekReposComp_Roo_Jpa_Entity {
    
    declare @type: AgentWeekReposComp: @Entity;
    
    declare @type: AgentWeekReposComp: @Table(name = "ABS_AGENT_WEEK_REPOS_COMP");
    
    @Version
    @Column(name = "version")
    private Integer AgentWeekReposComp.version;
    
    public Integer AgentWeekReposComp.getVersion() {
        return this.version;
    }
    
    public void AgentWeekReposComp.setVersion(Integer version) {
        this.version = version;
    }
    
}
