// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.Date;
import nc.noumea.mairie.abs.domain.AgentRecupCount;

privileged aspect AgentRecupCount_Roo_JavaBean {
    
    public Integer AgentRecupCount.getIdAgent() {
        return this.idAgent;
    }
    
    public void AgentRecupCount.setIdAgent(Integer idAgent) {
        this.idAgent = idAgent;
    }
    
    public Integer AgentRecupCount.getTotalMinutes() {
        return this.totalMinutes;
    }
    
    public void AgentRecupCount.setTotalMinutes(Integer totalMinutes) {
        this.totalMinutes = totalMinutes;
    }
    
    public Date AgentRecupCount.getLastModification() {
        return this.lastModification;
    }
    
    public void AgentRecupCount.setLastModification(Date lastModification) {
        this.lastModification = lastModification;
    }
    
}
