// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;
import nc.noumea.mairie.abs.domain.AgentRecupCount;

privileged aspect AgentRecupCount_Roo_Jpa_Entity {
    
    declare @type: AgentRecupCount: @Entity;
    
    declare @type: AgentRecupCount: @Table(name = "ABS_AGENT_RECUP_COUNT");
    
    @Id
    @SequenceGenerator(name = "agentRecupCountGen", sequenceName = "ABS_S_AGENT_RECUP_COUNT")
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "agentRecupCountGen")
    @Column(name = "ID_AGENT_RECUP_COUNT")
    private Integer AgentRecupCount.idAgentRecupCount;
    
    @Version
    @Column(name = "version")
    private Integer AgentRecupCount.version;
    
    public Integer AgentRecupCount.getIdAgentRecupCount() {
        return this.idAgentRecupCount;
    }
    
    public void AgentRecupCount.setIdAgentRecupCount(Integer id) {
        this.idAgentRecupCount = id;
    }
    
    public Integer AgentRecupCount.getVersion() {
        return this.version;
    }
    
    public void AgentRecupCount.setVersion(Integer version) {
        this.version = version;
    }
    
}
