// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;
import nc.noumea.mairie.abs.domain.AgentReposCompCount;

privileged aspect AgentReposCompCount_Roo_Jpa_Entity {
    
    declare @type: AgentReposCompCount: @Entity;
    
    declare @type: AgentReposCompCount: @Table(name = "ABS_AGENT_REPOS_COMP_COUNT");
    
    @Version
    @Column(name = "version")
    private Integer AgentReposCompCount.version;
    
    public Integer AgentReposCompCount.getVersion() {
        return this.version;
    }
    
    public void AgentReposCompCount.setVersion(Integer version) {
        this.version = version;
    }
    
}
