// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import nc.noumea.mairie.abs.domain.AgentWeekAlimManuelle;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentWeekAlimManuelle_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext(unitName = "absPersistenceUnit")
    transient EntityManager AgentWeekAlimManuelle.entityManager;
    
    public static final List<String> AgentWeekAlimManuelle.fieldNames4OrderClauseFilter = java.util.Arrays.asList("idAgentWeekAlimManuelle", "idAgent", "dateModification", "minutes", "motifCompteur");
    
    public static final EntityManager AgentWeekAlimManuelle.entityManager() {
        EntityManager em = new AgentWeekAlimManuelle().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AgentWeekAlimManuelle.countAgentWeekAlimManuelles() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AgentWeekAlimManuelle o", Long.class).getSingleResult();
    }
    
    public static List<AgentWeekAlimManuelle> AgentWeekAlimManuelle.findAllAgentWeekAlimManuelles() {
        return entityManager().createQuery("SELECT o FROM AgentWeekAlimManuelle o", AgentWeekAlimManuelle.class).getResultList();
    }
    
    public static List<AgentWeekAlimManuelle> AgentWeekAlimManuelle.findAllAgentWeekAlimManuelles(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM AgentWeekAlimManuelle o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, AgentWeekAlimManuelle.class).getResultList();
    }
    
    public static AgentWeekAlimManuelle AgentWeekAlimManuelle.findAgentWeekAlimManuelle(Integer idAgentWeekAlimManuelle) {
        if (idAgentWeekAlimManuelle == null) return null;
        return entityManager().find(AgentWeekAlimManuelle.class, idAgentWeekAlimManuelle);
    }
    
    public static List<AgentWeekAlimManuelle> AgentWeekAlimManuelle.findAgentWeekAlimManuelleEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AgentWeekAlimManuelle o", AgentWeekAlimManuelle.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<AgentWeekAlimManuelle> AgentWeekAlimManuelle.findAgentWeekAlimManuelleEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM AgentWeekAlimManuelle o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, AgentWeekAlimManuelle.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void AgentWeekAlimManuelle.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AgentWeekAlimManuelle.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AgentWeekAlimManuelle attached = AgentWeekAlimManuelle.findAgentWeekAlimManuelle(this.idAgentWeekAlimManuelle);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AgentWeekAlimManuelle.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AgentWeekAlimManuelle.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AgentWeekAlimManuelle AgentWeekAlimManuelle.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AgentWeekAlimManuelle merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
