// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import nc.noumea.mairie.abs.domain.AgentRecupCount;

privileged aspect AgentRecupCount_Roo_JavaBean {
    
    public Integer AgentRecupCount.getIdAgentRecupCount() {
        return this.idAgentRecupCount;
    }
    
    public void AgentRecupCount.setIdAgentRecupCount(Integer idAgentRecupCount) {
        this.idAgentRecupCount = idAgentRecupCount;
    }
    
}
