// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import nc.noumea.mairie.abs.domain.AgentWeekRecup;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentWeekRecup_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext(unitName = "absPersistenceUnit")
    transient EntityManager AgentWeekRecup.entityManager;
    
    public static final EntityManager AgentWeekRecup.entityManager() {
        EntityManager em = new AgentWeekRecup().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AgentWeekRecup.countAgentWeekRecups() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AgentWeekRecup o", Long.class).getSingleResult();
    }
    
    public static List<AgentWeekRecup> AgentWeekRecup.findAllAgentWeekRecups() {
        return entityManager().createQuery("SELECT o FROM AgentWeekRecup o", AgentWeekRecup.class).getResultList();
    }
    
    public static AgentWeekRecup AgentWeekRecup.findAgentWeekRecup(Integer idAgentWeekRecup) {
        if (idAgentWeekRecup == null) return null;
        return entityManager().find(AgentWeekRecup.class, idAgentWeekRecup);
    }
    
    public static List<AgentWeekRecup> AgentWeekRecup.findAgentWeekRecupEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AgentWeekRecup o", AgentWeekRecup.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void AgentWeekRecup.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AgentWeekRecup.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AgentWeekRecup attached = AgentWeekRecup.findAgentWeekRecup(this.idAgentWeekRecup);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AgentWeekRecup.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AgentWeekRecup.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AgentWeekRecup AgentWeekRecup.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AgentWeekRecup merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
