// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import nc.noumea.mairie.abs.domain.AgentWeekReposComp;

privileged aspect AgentWeekReposComp_Roo_JavaBean {
    
    public Integer AgentWeekReposComp.getIdAgentWeekReposComp() {
        return this.idAgentWeekReposComp;
    }
    
    public void AgentWeekReposComp.setIdAgentWeekReposComp(Integer idAgentWeekReposComp) {
        this.idAgentWeekReposComp = idAgentWeekReposComp;
    }
    
}
