// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import nc.noumea.mairie.abs.domain.AgentRecupCount;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentRecupCount_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext(unitName = "absPersistenceUnit")
    transient EntityManager AgentRecupCount.entityManager;
    
    public static final EntityManager AgentRecupCount.entityManager() {
        EntityManager em = new AgentRecupCount().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AgentRecupCount.countAgentRecupCounts() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AgentRecupCount o", Long.class).getSingleResult();
    }
    
    public static List<AgentRecupCount> AgentRecupCount.findAllAgentRecupCounts() {
        return entityManager().createQuery("SELECT o FROM AgentRecupCount o", AgentRecupCount.class).getResultList();
    }
    
    public static AgentRecupCount AgentRecupCount.findAgentRecupCount(Integer idAgentRecupCount) {
        if (idAgentRecupCount == null) return null;
        return entityManager().find(AgentRecupCount.class, idAgentRecupCount);
    }
    
    public static List<AgentRecupCount> AgentRecupCount.findAgentRecupCountEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AgentRecupCount o", AgentRecupCount.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void AgentRecupCount.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AgentRecupCount.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AgentRecupCount attached = AgentRecupCount.findAgentRecupCount(this.idAgentRecupCount);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AgentRecupCount.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AgentRecupCount.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AgentRecupCount AgentRecupCount.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AgentRecupCount merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
