// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import nc.noumea.mairie.abs.domain.AgentReposCompCount;

privileged aspect AgentReposCompCount_Roo_JavaBean {
    
    public Integer AgentReposCompCount.getIdAgentReposCompCount() {
        return this.idAgentReposCompCount;
    }
    
    public void AgentReposCompCount.setIdAgentReposCompCount(Integer idAgentReposCompCount) {
        this.idAgentReposCompCount = idAgentReposCompCount;
    }
    
}
