// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import nc.noumea.mairie.abs.domain.AgentWeekRecup;

privileged aspect AgentWeekRecup_Roo_JavaBean {
    
    public Integer AgentWeekRecup.getIdAgentWeekRecup() {
        return this.idAgentWeekRecup;
    }
    
    public void AgentWeekRecup.setIdAgentWeekRecup(Integer idAgentWeekRecup) {
        this.idAgentWeekRecup = idAgentWeekRecup;
    }
    
}
