// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.Date;
import nc.noumea.mairie.abs.domain.AgentWeekAlimManuelle;
import nc.noumea.mairie.abs.domain.MotifCompteur;

privileged aspect AgentWeekAlimManuelle_Roo_JavaBean {
    
    public Integer AgentWeekAlimManuelle.getIdAgentWeekAlimManuelle() {
        return this.idAgentWeekAlimManuelle;
    }
    
    public void AgentWeekAlimManuelle.setIdAgentWeekAlimManuelle(Integer idAgentWeekAlimManuelle) {
        this.idAgentWeekAlimManuelle = idAgentWeekAlimManuelle;
    }
    
    public Integer AgentWeekAlimManuelle.getIdAgent() {
        return this.idAgent;
    }
    
    public void AgentWeekAlimManuelle.setIdAgent(Integer idAgent) {
        this.idAgent = idAgent;
    }
    
    public Date AgentWeekAlimManuelle.getDateModification() {
        return this.dateModification;
    }
    
    public void AgentWeekAlimManuelle.setDateModification(Date dateModification) {
        this.dateModification = dateModification;
    }
    
    public int AgentWeekAlimManuelle.getMinutes() {
        return this.minutes;
    }
    
    public void AgentWeekAlimManuelle.setMinutes(int minutes) {
        this.minutes = minutes;
    }
    
    public MotifCompteur AgentWeekAlimManuelle.getMotifCompteur() {
        return this.motifCompteur;
    }
    
    public void AgentWeekAlimManuelle.setMotifCompteur(MotifCompteur motifCompteur) {
        this.motifCompteur = motifCompteur;
    }
    
}
