// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.Date;
import nc.noumea.mairie.abs.domain.AgentWeekRecup;

privileged aspect AgentWeekRecup_Roo_JavaBean {
    
    public Integer AgentWeekRecup.getIdAgent() {
        return this.idAgent;
    }
    
    public void AgentWeekRecup.setIdAgent(Integer idAgent) {
        this.idAgent = idAgent;
    }
    
    public int AgentWeekRecup.getMinutesRecup() {
        return this.minutesRecup;
    }
    
    public void AgentWeekRecup.setMinutesRecup(int minutesRecup) {
        this.minutesRecup = minutesRecup;
    }
    
    public Date AgentWeekRecup.getDateMonday() {
        return this.dateMonday;
    }
    
    public void AgentWeekRecup.setDateMonday(Date dateMonday) {
        this.dateMonday = dateMonday;
    }
    
    public Date AgentWeekRecup.getLastModification() {
        return this.lastModification;
    }
    
    public void AgentWeekRecup.setLastModification(Date lastModification) {
        this.lastModification = lastModification;
    }
    
}
