// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.Date;
import nc.noumea.mairie.abs.domain.BaseAgentCount;

privileged aspect BaseAgentCount_Roo_JavaBean {
    
    public Integer BaseAgentCount.getIdAgent() {
        return this.idAgent;
    }
    
    public void BaseAgentCount.setIdAgent(Integer idAgent) {
        this.idAgent = idAgent;
    }
    
    public int BaseAgentCount.getTotalMinutes() {
        return this.totalMinutes;
    }
    
    public void BaseAgentCount.setTotalMinutes(int totalMinutes) {
        this.totalMinutes = totalMinutes;
    }
    
    public Date BaseAgentCount.getLastModification() {
        return this.lastModification;
    }
    
    public void BaseAgentCount.setLastModification(Date lastModification) {
        this.lastModification = lastModification;
    }
    
}
