// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.Date;
import nc.noumea.mairie.abs.domain.BaseAgentWeekHisto;

privileged aspect BaseAgentWeekHisto_Roo_JavaBean {
    
    public Integer BaseAgentWeekHisto.getIdAgent() {
        return this.idAgent;
    }
    
    public void BaseAgentWeekHisto.setIdAgent(Integer idAgent) {
        this.idAgent = idAgent;
    }
    
    public int BaseAgentWeekHisto.getMinutes() {
        return this.minutes;
    }
    
    public void BaseAgentWeekHisto.setMinutes(int minutes) {
        this.minutes = minutes;
    }
    
    public Date BaseAgentWeekHisto.getDateMonday() {
        return this.dateMonday;
    }
    
    public void BaseAgentWeekHisto.setDateMonday(Date dateMonday) {
        this.dateMonday = dateMonday;
    }
    
    public Date BaseAgentWeekHisto.getLastModification() {
        return this.lastModification;
    }
    
    public void BaseAgentWeekHisto.setLastModification(Date lastModification) {
        this.lastModification = lastModification;
    }
    
}
