// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import nc.noumea.mairie.abs.domain.DemandeRecup;

privileged aspect DemandeRecup_Roo_JavaBean {
    
    public Integer DemandeRecup.getDuree() {
        return this.duree;
    }
    
    public void DemandeRecup.setDuree(Integer duree) {
        this.duree = duree;
    }
    
}
