// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import nc.noumea.mairie.abs.domain.DroitDroitsAgent;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DroitDroitsAgent_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext(unitName = "absPersistenceUnit")
    transient EntityManager DroitDroitsAgent.entityManager;
    
    public static final List<String> DroitDroitsAgent.fieldNames4OrderClauseFilter = java.util.Arrays.asList("idDroitDroitsAgent", "droit", "droitsAgent", "droitProfil");
    
    public static final EntityManager DroitDroitsAgent.entityManager() {
        EntityManager em = new DroitDroitsAgent().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long DroitDroitsAgent.countDroitDroitsAgents() {
        return entityManager().createQuery("SELECT COUNT(o) FROM DroitDroitsAgent o", Long.class).getSingleResult();
    }
    
    public static List<DroitDroitsAgent> DroitDroitsAgent.findAllDroitDroitsAgents() {
        return entityManager().createQuery("SELECT o FROM DroitDroitsAgent o", DroitDroitsAgent.class).getResultList();
    }
    
    public static List<DroitDroitsAgent> DroitDroitsAgent.findAllDroitDroitsAgents(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM DroitDroitsAgent o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, DroitDroitsAgent.class).getResultList();
    }
    
    public static DroitDroitsAgent DroitDroitsAgent.findDroitDroitsAgent(Integer idDroitDroitsAgent) {
        if (idDroitDroitsAgent == null) return null;
        return entityManager().find(DroitDroitsAgent.class, idDroitDroitsAgent);
    }
    
    public static List<DroitDroitsAgent> DroitDroitsAgent.findDroitDroitsAgentEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM DroitDroitsAgent o", DroitDroitsAgent.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<DroitDroitsAgent> DroitDroitsAgent.findDroitDroitsAgentEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM DroitDroitsAgent o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, DroitDroitsAgent.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void DroitDroitsAgent.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void DroitDroitsAgent.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            DroitDroitsAgent attached = DroitDroitsAgent.findDroitDroitsAgent(this.idDroitDroitsAgent);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void DroitDroitsAgent.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void DroitDroitsAgent.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public DroitDroitsAgent DroitDroitsAgent.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        DroitDroitsAgent merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
