// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;
import nc.noumea.mairie.abs.domain.DroitDroitsAgent;

privileged aspect DroitDroitsAgent_Roo_Jpa_Entity {
    
    declare @type: DroitDroitsAgent: @Entity;
    
    declare @type: DroitDroitsAgent: @Table(name = "ABS_DROIT_DROITS_AGENT");
    
    @Version
    @Column(name = "version")
    private Integer DroitDroitsAgent.version;
    
    public Integer DroitDroitsAgent.getVersion() {
        return this.version;
    }
    
    public void DroitDroitsAgent.setVersion(Integer version) {
        this.version = version;
    }
    
}
