// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import nc.noumea.mairie.abs.domain.Droit;
import nc.noumea.mairie.abs.domain.DroitDroitsAgent;
import nc.noumea.mairie.abs.domain.DroitProfil;
import nc.noumea.mairie.abs.domain.DroitsAgent;

privileged aspect DroitDroitsAgent_Roo_JavaBean {
    
    public Integer DroitDroitsAgent.getIdDroitDroitsAgent() {
        return this.idDroitDroitsAgent;
    }
    
    public void DroitDroitsAgent.setIdDroitDroitsAgent(Integer idDroitDroitsAgent) {
        this.idDroitDroitsAgent = idDroitDroitsAgent;
    }
    
    public Droit DroitDroitsAgent.getDroit() {
        return this.droit;
    }
    
    public void DroitDroitsAgent.setDroit(Droit droit) {
        this.droit = droit;
    }
    
    public DroitsAgent DroitDroitsAgent.getDroitsAgent() {
        return this.droitsAgent;
    }
    
    public void DroitDroitsAgent.setDroitsAgent(DroitsAgent droitsAgent) {
        this.droitsAgent = droitsAgent;
    }
    
    public DroitProfil DroitDroitsAgent.getDroitProfil() {
        return this.droitProfil;
    }
    
    public void DroitDroitsAgent.setDroitProfil(DroitProfil droitProfil) {
        this.droitProfil = droitProfil;
    }
    
}
