// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package nc.noumea.mairie.abs.domain;

import nc.noumea.mairie.abs.domain.MotifCompteur;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MotifCompteur_Roo_Configurable {
    
    declare @type: MotifCompteur: @Configurable;
    
}
